apiVersion: v1
kind: Service
metadata:
  name: dns-svc
  namespace: {{.Values.namespace}}
spec:
  ports:
    - name: dns-svc-port
      port: 80
      targetPort: dns-port
  selector:
    app: {{.Values.deploy.app}}
  type: {{.Values.service.type}}
